### PR TITLE
Update dev tools

### PR DESCRIPTION
**Pull request by rkalis**
This PR updates the developer tooling list with the following changes:

- Change Fullstack to bch-js under all-in-one, move fullstack to REST APIs.
- Remove BCHD, bchwallet, and neutrino. Afaict these aren't really SDKs (maybe neutrino is), so if BCHD/bchwallet is on there, other nodes should probably be as well, but I'd say the nodes shouldn't be on there.
- Add bitcoin-kit-ios, bitcoin-kit-android and bitbox-flutter to all-in-one
- Add the Rust bitcoin-cash crate and Haskell haskoin-core library to "data and utilities"
- Add iguana (Rust/JS Bitcoin Script debugger) to "smart contracts"
- Add slpjs to "tokens"
- Add Fountainhead.cash to REST APIs

This PR is just my suggestion, so feel free to make any changes as you see fit or ask me to make any changes.

Also, it's not super clear to me where the division is between "all-in-one" and "data and utilities" (e.g. I think libauth and bitcore-lib-cash have very similar functionality).

Cheers!

### CODE REVIEW

**Review by merc1er — APPROVED** [review]
Code looks good. Only the Swift logo looks a bit weird (different from [swift.org](https://swift.org)).

Let's wait for @imaginaryusername and @emergent-reasons take on this before merging.

**Comment by rkalis** [comment]
Good point about the swift logo. Updated it.

**Review by emergent-reasons — APPROVED** [review]
LGTM

I hate github approval system :D

**Comment by merc1er** [comment]
Thank you @rkalis

**Pull request merged**
