### PR TITLE
Add Electron Cash mobile wallet

### PR DESCRIPTION
**Pull request by hieu-van**
Pretty much copy & paste.

### CODE REVIEW

**Review by merc1er — APPROVED** [review]
Works for me. What do you think @imaginaryusername?

**Comment by imaginaryusername** [comment]
Should we link to electroncash.org, or to the app/google store entries?

**Comment by hieu-van** [comment]
I think we should link to the wallet's homepage, just in case visitors want to learn more about the wallet… The Play Store link is already on the homepage anyway.

**Comment by merc1er** [comment]
> The Play Store link is already on the homepage anyway.

The App Store version is there too.  
Also we currently only have a "mobile" section, and all other wallets link to the website, not app stores directly @imaginaryusername

**Comment by imaginaryusername** [comment]
No further comments, merge away!

**Pull request merged**
