### PR TITLE
Added KeepKey to list of hardware wallets. Update wallets.html.

### PR DESCRIPTION
**Pull request by greatwolf**
Added KeepKey under hardware wallet since it has bch support. Addresses issue #61.

### CODE REVIEW

**Comment by greatwolf** [comment]
Would anyone mind taking a look at my PR?

**Comment by merc1er** [comment]
> Would anyone mind taking a look at my PR?

I still think this shouldn't be merged until the official clients comes out of beta.

@imaginaryusername what do you think?

**Comment by imaginaryusername** [comment]
Not sure what's the relationship between their different clients, but found this on the website:

image

so the current "official way to access" seems to be entirely web-based at https://app.shapeshift.com

someone known with a keepkey needs to test this and report if it works with BCH.

**Comment by greatwolf** [comment]
> I still think this shouldn't be merged until the official client comes out of beta.
> 
> @imaginaryusername what do you think?

Which client are you referring to? If you're talking about app.shapeshift.com, it already has bch support enabled and operational.

**Comment by greatwolf** [comment]
I'll share a couple screenshots here to show that it's working, at least the basic sending and receiving part of it is fine.

image
image
image

When I get a chance I'll also test ElectrumCash with my KeepKey and will report back. If it's anything like the regular electrum or  Dash's fork of electrum then it should work fine.

**Comment by greatwolf** [comment]
Okay I just tested my KeepKey on Electron-Cash-4.2.12, current latest at time of this posting. It's able to communicate with and verify the pin as well as passphrase on my KeepKey. I'm able to send and receive fine using addresses generated from the device. All the transaction history shows up as well.

From what I can tell, everything works as it should.

**Comment by danger89** [comment]
> Not sure what's the relationship between their different clients, but found this on the website:
> 
> image
> 
> so the current "official way to access" seems to be entirely web-based at https://app.shapeshift.com
> 
> someone known with a keepkey needs to test this and report if it works with BCH.

Yea they do support BCH. But why is it using a DEX online instead of an offline open source app?

**Comment by greatwolf** [comment]
> 
> Yea they do support BCH. But why is it using a DEX online instead of an offline open source app?

yeah, it's not ideal. The quick backstory is before Shapeshift acquired KeepKey the main way to access it was through the Chrome Extension. After the acquisition they basically wanted to migrate users onto their shapeshift platform. Unfortunately not all the features were made available, like for example bitcoin gold, digibyte and some other altcoin support.

I needed a way to access those too and since it's clearly not a firmware support issue, it was a UI interface issue, I just took the original Chrome Extension source as the starting base and started improving and maintaining it myself.

That all said, there is work being done in the shapeshift community since turning into a DEX/DAO setup, specifically highlander is working on a standalone webapp client. It's still in it's early stages you can find it here: https://github.com/keepkey/keepkey-desktop. That gets you closer to an open-source standalone app you can use.

I haven't tested that though, I've only confirmed app.shapeshift.com works, ElectronCash works and the KKClient fork I've been maintaining works.

**Comment by SayoshiNakamario** [comment]
Have used a Keepkey with Electron Cash without issue for years. Not that I'm an anybody :)

**Comment by imaginaryusername** [comment]
@SayoshiNakamario I think you definitely qualify as "known community member" tbh, can you give the shapeshift webapp a quick try? :)

**Comment by SayoshiNakamario** [comment]
Verified sending/receiving with Keepkey on shapeshift's webapp works for BCH, but only on Chrome (Version 107.0.5304.123), Firefox (107.0.1) would not detect the Keepkey. I Shapeshift has only ever officially supported Chrome though.

**Comment by imaginaryusername** [comment]
Thank you. @merc1er I think it's safe to recommend a merge.

**Review by merc1er — APPROVED** [review]

**Comment by greatwolf** [comment]
> Verified sending/receiving with Keepkey on shapeshift's webapp works for BCH, but only on Chrome (Version 107.0.5304.123), Firefox (107.0.1) would not detect the Keepkey. I Shapeshift has only ever officially supported Chrome though.

yeah, I think any Chromium-based browser should work. I think the issue stems from firefox not supporting the webusb api interface. Without that any site or webapp won't be able to communicate with KeepKey or any other custom usb device for that matter.

**Comment by danger89** [comment]
> @SayoshiNakamario I think you definitely qualify as "known community member" tbh, can you give the shapeshift webapp a quick try? :)

He is? His account seems almost not used in GitHub and pretty new actually.

**Comment by imaginaryusername** [comment]
> > @SayoshiNakamario I think you definitely qualify as "known community member" tbh, can you give the shapeshift webapp a quick try? :)
> 
> He is? His account seems almost not used in GitHub and pretty new actually.

He's the builder of helpme.cash

**Pull request merged**
