### PR TITLE
Add programming languages icons

### PR DESCRIPTION
**Pull request by merc1er**
This also adds a new `REST APIs` section with (for now) rest.Bitcoin.com and GetBlock.io

### CODE REVIEW

**Review by emergent-reasons — APPROVED** [review]
Looks great and I like how you added something explicit for API and CLI. I'm not sure if `C:\` Is the best icon for terminal people who probably tend to be linux/osx but it definitely works.

**Comment by merc1er** [comment]
> 'm not sure if C:\ Is the best icon for terminal

Yes, definitely. I am not using Windows myself, but that was the only decent icons I found on ICONS8. I'll try something else.

**Comment by merc1er** [comment]
@emergent-reasons CLI icon updated, let me know if you prefer this ;)

**Comment by emergent-reasons** [comment]
> @emergent-reasons CLI icon updated, let me know if you prefer this ;)

Noice.

**Pull request merged**
